name: "Publish to PYPI"

on:
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g., v0.1.0
      - v*
    branches:
      - main

jobs:
  run:
    runs-on: self-hosted
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # --- Step 1: PyPI ---
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Build & Publish to PyPI
        run: |
          uv python install 3.12
          uv build
          uv publish
    # --- Step 2: Conda (using Local Path) ---
      - name: Build Conda recipe
        run: rattler-build generate-recipe pypi jp_tools > conda.recipe/recipe.yaml
      - name: Build Conda package
        uses: prefix-dev/rattler-build-action@v0.2.34

      - name: Upload packages to Anaconda
        run: |
          for pkg in $(find output -type f \( -name "*.conda" -o -name "*.tar.bz2" \) ); do
            echo "Uploading ${pkg}"
            rattler-build upload anaconda -o gitinference "${pkg}" --force
          done
        env:
          ANACONDA_API_KEY: ${{ secrets.ANACONDA_API_KEY }}
